#!/bin/sh

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-fs
. /usr/libexec/os-helpers-logging

nvmewait_enabled() {
    return 0
}

nvmewait_run() {
    C=0
    delay=1

    # Using -b makes the initramfs crash
    while [ ! -e /dev/nvme0n1p1 ];
    do

        if [ "$C" == 10 ]; then
            echo "Timeout while waiting for nvme. Fsck may not run on all partitions"
            break
        fi

        debug "Attempt ${C}: Waiting ${delay} second for nvme to initialize..."
        sleep ${delay}

        C=$(( $C + 1 ))
    done
}
