#!/bin/sh
set -o errexit

# Script which writes the appropriate
# device tree with embedded cmdline
# and updates the kernel, as well as
# the rest of the bootloader binaries

. /usr/libexec/os-helpers-fs

DURING_UPDATE=${DURING_UPDATE:-0}
declare -a UPDATED_PARTITIONS=()
bootloader_device="/dev/mtdblock0"
bootloader_blob="/opt/tegra-binaries/boot0.img.gz"

info_log()
{
    echo "[INFO] $@"
}

existing_bootloader_md5sum=$(dd if=$bootloader_device bs=1M status=none | md5sum | awk '{print $1}')
update_bootloader_md5sum=$(md5sum $bootloader_blob | awk '{print $1}')

if [ ! "$existing_bootloader_md5sum" = "$update_bootloader_md5sum" ]; then
    info_log "Will clear bootloader device before the update"
    flash_erase /dev/mtd0 0 0 || true
    info_log "Updating update bootloader device"
    zcat $bootloader_blob > $bootloader_device
    info_log "Updated bootloader device"
else
    info_log "No need to update bootloader device"
fi

# Sync internal memory
sync /dev/mtdblock0
