#!/bin/sh
set -o errexit

# Script which writes the appropriate
# device tree with embedded cmdline
# and updates the kernel, as well as
# the rest of the bootloader binaries

. /usr/libexec/os-helpers-fs

DURING_UPDATE=${DURING_UPDATE:-0}
declare -a UPDATED_PARTITIONS=()
bootloader_device="/dev/mtdblock0"
bootloader_blob="/opt/tegra-binaries/boot0.img.gz"
partspec="/opt/tegra-binaries/partition_specification194_nxde.txt"

info_log()
{
    echo "[INFO] $@"
}


update_needed() {
    current_update_file=${1}
    device=${2}
        update_size=$(ls -al $current_update_file | awk '{print $5}')
        update_md5sum=$(md5sum $current_update_file | awk '{print $1'})
        existing_md5sum=$(dd if=$device bs=1 count=$update_size status=none | md5sum | awk '{print $1}')

        if [ ! "$existing_md5sum" = "$update_md5sum" ]; then
            echo 1
        else
            echo 0
        fi
}


partitions=$(cat "${partspec}")

for n in ${partitions}; do
    part_name=$(echo $n | cut -d ':' -f 1)
    file_name=$(echo $n | cut -d ':' -f 2)

    if [ -z "${part_name##*_b}" ] || [ $file_name = "none.bin" ]; then
        continue
    fi

    file_path=$(get_state_path_from_label $part_name)

    if [ "x$file_path" = "x" ]; then
        continue
    fi

    dst="${file_path}"
    src="/opt/tegra-binaries/$file_name"
    if [ -e ${dst} ]; then
        if [ $(update_needed $src $dst) -eq 1 ]; then
            info_log "Will update ${dst} ..."
            dd if=${src} of="${dst}"
            info_log "Updated ${dst}"
        else
            info_log "No need to update ${dst}"
        fi
    else
        info_log "Partition ${dst} not found"
    fi
done

# These never match because tegra bootloaders always
# write to the SPI flash
info_log "Will update bootloader device"
flash_erase /dev/mtd0 0 0 || true
zcat $bootloader_blob > $bootloader_device

# Sync internal memory
sync /dev/mmcblk0
sync /dev/mtdblock0
